import type { Metadata } from "next";
import styles from "./layout.module.scss";
import { Poppins } from "next/font/google";
import { Banner } from "./components/banner/banner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={poppins.className}>
      <body className={styles.body}>
        <div className={styles.header}><Banner /></div>
        <div className={styles.content}>{children}</div>
      </body>
    </html>
  );
}
